version: "3.8"
services:
  mysql:
    image: mysql:8.2
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always

volumes:
  mysql_data: {}
