version: "3.8"
services:
  mysql:
    image: mysql:8.2
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pokedraft
      - MYSQL_USER=aloan93
      - MYSQL_PASSWORD=aloan93
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306/tcp"
    restart: always

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always

volumes:
  mysql_data: {}
